import time

from qgis.core import QgsField
from PyQt5.QtCore import QVariant

from processors.CatchmentProcessor import CatchmentProcess
from processors.DemandSiteProcessor import DemandSiteProcess
from processors.GroundwaterProcessor import GroundwaterProcess
from postprocessors.GeoChecker import GeoChecker
from postprocessors.SuperpositionCheck import SuperpositionCheck
from processors.RiverProcessor import RiverProcess
from  utils.Visualizer import *
import settings

class AppKernel():
    """
    Initializes groundwater, catchment, rivers and demand sites processors. In addition, it initializes the kernel
    that processes the geometry, which will be used to validate the information from the geometry processor.

    It receives the inputs from UI interfaces.

    * Config file: ./config/config.json


    Attributes:
    ----------
    geo_processor : GeoKernel
        Used to read the surface scheme geometry (node and arc files).

    catchment_processor : CatchmentProcess
        Used to process catchment map.

    groundwater_processor : GroundwaterProcess
        Used to process groundwater map.

    demand_site_processor : DemandSiteProcess
        Used to process demand sites main map. That map is obtained from the surface scheme.
        Additionally it also processes additional maps with demand site areas.

    river_processor : RiverProcess
        Used to process the segments map obtained from rivers in surface scheme.

    consolidate_cells : Dict[namedtuple<Cell>, Dict[str, Any]]
        Used to consolidate groundwater, catchment, river and demand site cells in order to check them only once.

    config : ConfigApp
        Used to access to configuration parameters (constants, texts, input columns, ...).

    summary : SummaryInfo
        Used to access the results generated by AppKernel (errors, warnings, input parameters, statistics) and
        deliver them in a standard way.

    stats : Dict[str, str]
        Used to store the general process basic statistics.

    _err : ErrorManager
        Used to store errors and warnings found while running.

    __debug : bool
        Not used.

    _feature_type : str
        Text used to identify the main process (value: self.config.type_names[self.__class__.__name__]).


    Methods:
    -------
    get_feature_type(self)
        Get a name to identify processors or main program.

    set_config_field(self, catchment_field, modflow_field, groundwater_field, demand_site_field)
        Sets  geometry name columns in input maps to processors.

    export_to_shapefile(self, map_name, output_path)
        Export the 'map_name' map in ESRI Shapefile format (.shp) to the 'output_path' path.

    get_consolidate_cells(self)
        Unify all intersecting cells in processors in order to check them only once.

    init_linkage_file(self, linkage_name, linkage_new_name)
        Initialize the final grid map with the necessary and informative columns. The 'linkage_name' parameter
        is the input groundwater grid map and 'linkage_new_name' parameter is the final map name.

    mark_linkage_active(self, linkage_name, save_changes)
        Saves the cells information in the final map metadata ('linkage_name') to export.
        The 'save_changes' parameter sets the number of cells to review before committing the transaction.

    set_map_names(self)
        In case there is no error in the input files, register these files in the different processors to relate them
        to the vector maps to be imported.

    set_origin_in_node_arc_maps(self, map_names: list)
        Set lower left edge in vector map list 'map_names'.

    run(self)
        Runs the correct order of methods to perform the processing of the implemented processors.

    """

    def __init__(self, debug: bool = False):
        self.debug = debug

        self.catchment_processor = CatchmentProcess(debug=self.debug)
        self.groundwater_processor = GroundwaterProcess(debug=self.debug)
        self.river_processor = RiverProcess(debug=self.debug)
        self.demand_site_processor = DemandSiteProcess(debug=self.debug)
        self.stats = {}
        self.visualizer = Visualizer()

    #     ## GeoCheker (tengo que importar el traducido)
    #     self.config = settings
    #     self.consolidate_cells = None
    #     self.geo_checker = GeoChecker(checks=
    #                     [
    #                         SuperpositionCheck(base_feature='groundwater', secondary_feature='catchment', config=self.config),
    #                         SuperpositionCheck(base_feature='groundwater', secondary_feature='demand_site', config=self.config)
    #                     ]
    #         , config= self.config
    #         )
        
    # def run_geo_checker(self, result_path: str):
    #     self.geo_checker.set_result_path(result_path)
    #     self.geo_checker.setup(consolidate_cells=self.consolidate_cells, arcs=self.geo_processor.arcs, nodes=self.geo_processor.nodes)
    #     self.geo_checker.run()

    def consolidate_grid_attributes(self, grid_layer):
        """
        Toma los datos procesados de todas las entidades y los escribe 
        en la tabla de atributos de la capa de la malla.
        """

        # 1. Definir la estructura de columnas exacta que exige WEAP/MODFLOW
        # Ajusta los nombres de las llaves ('CATCH', 'DS1', etc.) según tus settings.py
        columnas_exportacion = {
            'gw': ['GW'],
            'catchment': ['CATCH'],
            'river': ['RIVER'],
            'ds': ['DS1', 'DS2', 'DS3', 'DS4']
        }

        # 2. Asegurarnos de que las columnas existan en la capa de la malla
        provider = grid_layer.dataProvider()
        campos_actuales = [field.name() for field in grid_layer.fields()]
        campos_nuevos = []

        for grupo_columnas in columnas_exportacion.values():
            for nombre_columna in grupo_columnas:
                if nombre_columna not in campos_actuales:
                    campos_nuevos.append(QgsField(nombre_columna, QVariant.String, len=50))
        
        if campos_nuevos:
            # Agregamos las columnas faltantes físicamente al Shapefile/Memoria
            provider.addAttributes(campos_nuevos)
            grid_layer.updateFields()

        # 3. Preparar el lote de actualizaciones
        # PyQGIS usa un diccionario { ID_Entidad: { Indice_Columna: Nuevo_Valor } }
        lote_actualizacion = {}
        
        # Necesitamos saber el índice (0, 1, 2...) de cada columna para el lote
        indices_columnas = {field.name(): grid_layer.fields().indexOf(field.name()) for field in grid_layer.fields()}

        # 4. Iterar sobre la malla y recolectar los datos ganadores
        for feature in grid_layer.getFeatures():
            fid = feature.id()
            
            # Asumimos que la celda se identifica por su fila y columna
            # Deberás ajustar 'row' y 'col' al nombre real de tus columnas en la malla
            from collections import namedtuple
            Cell = namedtuple('Cell', ['row', 'col'])
            celda_actual = Cell(feature['row'], feature['col'])

            atributos_celda = {}

            # Extraemos los datos empaquetados de cada procesador llamando a la función que limpiamos antes
            # Nota: Necesitarás tener guardados los map_name que se usaron en el run()
            
            # Ejemplo para Groundwater
            if self.groundwater_processor:
                datos_gw = self.groundwater_processor.format_cell_data_for_export(
                    cell=celda_actual, map_name=self.nombre_mapa_gw, 
                    export_column_names=columnas_exportacion['gw']
                )
                atributos_celda.update(datos_gw)

            # Ejemplo para Catchment
            if self.catchment_processor:
                datos_catchment = self.catchment_processor.format_cell_data_for_export(
                    cell=celda_actual, map_name=self.nombre_mapa_catchment, 
                    export_column_names=columnas_exportacion['catchment']
                )
                atributos_celda.update(datos_catchment)

            # Ejemplo para Ríos
            if self.river_processor:
                datos_river = self.river_processor.format_cell_data_for_export(
                    cell=celda_actual, map_name=self.nombre_mapa_river, 
                    export_column_names=columnas_exportacion['river']
                )
                atributos_celda.update(datos_river)

            # Ejemplo para Sitios de Demanda (Pozos)
            if self.demand_site_processor:
                datos_ds = self.demand_site_processor.format_cell_data_for_export(
                    cell=celda_actual, map_name=self.nombre_mapa_ds, 
                    export_column_names=columnas_exportacion['ds'],
                    is_demand_site=True
                )
                atributos_celda.update(datos_ds)

            # 5. Mapear los nombres de columnas a sus índices numéricos para PyQGIS
            cambios_para_esta_celda = {}
            for nombre_col, valor in atributos_celda.items():
                if nombre_col in indices_columnas:
                    idx = indices_columnas[nombre_col]
                    cambios_para_esta_celda[idx] = valor
            
            # Guardamos los cambios de esta celda en el gran lote maestro
            if cambios_para_esta_celda:
                lote_actualizacion[fid] = cambios_para_esta_celda

        # 6. Ejecutar la escritura en bloque (¡El momento de la verdad!)
        # startEditing() y commitChanges() manejan las transacciones seguras en QGIS
        grid_layer.startEditing()
        provider.changeAttributeValues(lote_actualizacion)
        grid_layer.commitChanges()        



    def run(self, grid_layer, layers_dict, output_path, run_geochecker: bool = False):
        ts = time.time()

        # -------------------------------------------------------------------------------
        # Catchments Logic
        # -------------------------------------------------------------------------------
        # import files to vector maps
        self.catchment_processor.run(grid_layer, **layers_dict['catchment'])

        # -------------------------------------------------------------------------------
        # GWS Logic
        # -------------------------------------------------------------------------------
        # import files to vector maps
        self.groundwater_processor.run(grid_layer, **layers_dict['gw'])

        # -------------------------------------------------------------------------------
        # Demand Sites Logic
        # -------------------------------------------------------------------------------
        # import files to vector maps
        self.demand_site_processor.run(grid_layer, **layers_dict['ds'])

        # -------------------------------------------------------------------------------
        # Rivers Logic
        # -------------------------------------------------------------------------------
        # import files to vector maps
        self.river_processor.run(grid_layer, **layers_dict['river'])

        # -------------------------------------------------------------------------------
        # General and Results Logic
        # -------------------------------------------------------------------------------
        # make a linkage map copy and format with the base linkage cols

        self.consolidate_grid_attributes(grid_layer)

        ## no implementado aun
        if run_geochecker:
            self.run_geo_checker(output_path)


        te = time.time()
        self.stats['TOTAL_TIME'] = f"{te - ts:.2f} seg"

        self.visualizer.set_result_path(output_path)
        

