from abc import abstractmethod, ABCMeta
import processing
from qgis.core import QgsVectorLayer


class FeatureProcess(metaclass=ABCMeta):
    """
        It is the feature processors parent class. Contains the generic logic of all processors.
        Currently 4 processors are implemented for vector maps of: catchments, groundwater, rivers and demand sites.

        Imports a shapefile to convert it into a vector map in a GRASS session.
        Processes vector map geometries using GRASS tools.
        Validates that geometries found are present in the surface scheme (node map and arc map).
        Linking geometries with groundwater grid cells.
        Creates a vector map with its final grid metadata.
        Export the map with final grid using the ESRI Shapefile (SHP) format and metadata structure
        needed by WEAP: (row, col, GW, CATCH, RIVER, DS1, DS2, DS3, DS4)


        Attributes:
        ----------
        geo : GeoKernel
            Used to access geometries defined on surface scheme.

        cells : Dict[namedtuple<Cell>, Dict[str, Dict[str, str|int]]
            It is used to store cell-feature relationship. Because a cell can be intersected by more than one
            map geometry, access is given by: [cell] -> [geo_intersected] -> [cell_feature_relationship_data].
            Structure and values stored depends on feature type, so details are in the processor classes.

        cell_ids: Dict[namedtuple<Cell>, Dict[str, str|int|List<data>]]
            Store for each cell the geometry (or geometries) that be stored in final file.
            In case more than one geometry of the same feature type intersects the same cell, the criterion used to
            select it (or them) is implemented in '_cell_order_criteria_default(...)' method.
            The following data is stored:
                - 'number_of_data': columns number to use in final file.
                - 'cell_id': cell id . (id in GW grid's vector map)
                - 'row': cell row.
                - 'col': cell column.
                - 'data': list with the data (or data set) to be stored. It is obtained from 'cells' variable.

        _err : ErrorManager
            Stores and manage errors and warnings.

        stats : Dict[str, str]
            Stores basic statistics (# of geometry, # wells, etc.).

        summary : SummaryInfo
            Used to access the execution results (errors, warnings, input parameters, statistics.) generated by
            feature type and format them in a standard way.

        _feature_type : str
            Used to identify the feature type to process (default: self.config.type_names[self.__class__.__name__])

        _features_by_map : Dict[str, str]
            Stores geometry names by their vector map name. Indexed by vector name.


        Methods:
        -------
        run(self, linkage_name: str)
            Executes the correct tasks order to process the feature type. Imports map, validate it with surface scheme,
            and intersects feature map(s) with groundwater grid map ('linkage_name' parameter) to establish
            cell-gemetry relationship.

        import_maps(self, verbose: bool = False, quiet: bool = True)
            Imports ESRI Shapefile(s) as GRASS vector map(s).
            ('verbose' and 'quiet' parameters used for debugging).

        check_names_with_geo(self)
            Verifies that feature names of the main map exist in the surface scheme (arc and node maps).

        check_names_between_maps(self). En caso de que no exista lo reporta como error.
            Checks that feature names exist only on one map.
            It reports it as an error if it finds a name on two or more maps (for example, between informative DS maps).

        inter_map_with_linkage(self, linkage_name, snap='1e-12', verbose: bool = False, quiet: bool = True)
            Intersects a vector map with the groundwater grid vector, using a GRASS platform tool (v.overlay).
            The 'linkage_name' parameter identifies the final grid and the 'snap' parameter allows you to do more
            detailed (but slower) intersection.

        make_grid_cell(self)
            Stores cell-feature relationship using the intersection between a vector map and groundwater grid map.

        make_cell_data_by_main_map(self, map_name, inter_map_name, inter_map_geo_type)
            Create the structure that stores features data of a main map.
            A main map generates at least one mandatory column in the final file metadata (even if its value is NULL).
            This method must be overwritten by each class that inherits from it.

        make_cell_data_by_secondary_maps(self, map_name, inter_map_name, inter_map_geo_type)
            Create the structure that stores features data of a secondary map.
            A secondary map generates at least one informative column (non-mandatory) in the final file metadata.
            (Currently, this case happen for demand site areas maps.)
            This method must be overwritten by each class that inherits from it.

        get_data_to_save(self, cell, main_data: bool = True)
            Returns 'cell' data. The 'main_data' parameter has by default the value True, which referes to
             main map data.

        append_error(self, msg: str = None, msgs: list = None, typ: str = None, is_warn: bool = False, code: str = '')
            Logs an error with message (msg) or messages (msgs) parameters. The 'typ' parameter identifies feature type
            associated with the error (groundwater, catchment, demand_site, river, main).
            In case of being an error, 'is_warn' is False or True in warning case.
            The 'code' parameter is used to give a code to errors or warnings.

        get_summary(self)
            Returns an summary with input parameters used in processing, errors / warnings and
            associated statistics.

        """

    def __init__(self, debug: bool = False):
        self.cells = {}
        self.cell_ids = {}
        self.cells_by_map = {}

        self.__debug = debug
        self._feature_type = self.__class__.__name__

        # stats
        self.stats = {}

    @staticmethod
    ## ordena los poligonos/lineas de una celda y los devuelve como lista
    def _cell_order_criteria_default(cell, cells_dict, by_field='area'):
        area_targets = cells_dict[cell]
        area_targets_sorted = sorted(area_targets.items(), key=lambda x: x[1][by_field], reverse=True)
        area_targets_sorted = [area_target for area_key, area_target in area_targets_sorted]

        return area_targets_sorted  # (key, data_key)

    # acumula los fragmentos en self.cells
    def _set_cell(self, cell, area_name, data, by_field='area'):
        if cell in self.cells:
            # watch if exist catchment
            if area_name in self.cells[cell]:
                area_area = data[by_field]
                self.cells[cell][area_name][by_field] += area_area
            else:
                self.cells[cell][area_name] = data
        else:
            self.cells[cell] = {}

            self.cells[cell][area_name] = data

    #ordena las celdas procesadas y las guarda en otro arreglo
    def _set_cell_by_criteria(self, criteria_func=None, by_field='area'):
        # watch what is the best area by criteria for a cell
        if criteria_func is None:
            # Ordena los datos de la celda de mayor a menor basándose en 'by_field'
            criteria_func = lambda c, all_cells, by_field: sorted(
                all_cells[c].values(), 
                key=lambda item: item.get(by_field, 0), 
                reverse=True
            )

        for cell in self.cells:
            area_targets_ordered = criteria_func(cell, self.cells, by_field=by_field)

            self.cell_ids[cell] = {
                'number_of_data': len(area_targets_ordered),
                'cell_id': area_targets_ordered[0]['cell_id'],
                'row': cell.row,
                'col': cell.col,
                'data': area_targets_ordered
            }

    #@main_task
    def inter_map_with_linkage(self, source_layer, grid_layer, col_name_source):
        """
        Calcula la intersección espacial entre una capa vectorial (Cuencas, Ríos, etc.)
        y la capa de la Malla MODFLOW (grid_layer).
        Devuelve una nueva capa vectorial temporal (en memoria) con el resultado.
        """


        # 1. Validación temprana
        if not source_layer.isValid() or not grid_layer.isValid():
            raise ValueError(f"Error: Una de las capas no es válida ({source_layer.name()} o {grid_layer.name()})")

        # 2. Filtrado de geometrías sin nombre (Reemplaza a extract_map_with_condition)
        # En QGIS, simplemente creamos una consulta SQL ligera
        source_layer.setSubsetString(f'"{col_name_source}" IS NOT NULL AND "{col_name_source}" != \'\'')

        # 3. El Geoprocesamiento Nativo de QGIS (Reemplaza a v.overlay de GRASS)
        # Usamos el algoritmo nativo 'native:intersection' que es altamente optimizado
        params = {
            'INPUT': source_layer,
            'OVERLAY': grid_layer,
            'INPUT_FIELDS': [], # Dejamos vacío para mantener todos los campos
            'OVERLAY_FIELDS': [], 
            'OVERLAY_FIELDS_PREFIX': '',
            'OUTPUT': 'memory:' # Guardamos el resultado en la memoria RAM, no en el disco
        }

        try:
            # Ejecutamos el algoritmo
            result = processing.run("native:intersection", params)
            intersected_layer = result['OUTPUT']
            
            # Limpiamos el filtro SQL de la capa original para no afectarla
            source_layer.setSubsetString('')
            
            return False, intersected_layer # (Error=False, Capa Resultante)

        except Exception as e:
            # Restaurar el filtro por si acaso
            source_layer.setSubsetString('')
            raise RuntimeError(f"Fallo crítico al intersectar {source_layer.name()} con {grid_layer.name()}. Detalle: {e}")


    ##Returns 'cell' data. The 'main_data' parameter 
    # has by default the value True, which referes to
    ##main map data. 
    ## formatea la lista en formato shapefile
    ## cols_number = self.config.get_columns_to_save(feature_type=self.get_feature_type()), busca el COLUMNS_FOR_FEATURE de config

    def get_data_to_save(self, cell, map_name, main_data=True, is_demand_site=False, export_column_names=None):
        
        #main_map = self.get_main_map_name(only_name=True, imported=True)
        col_data = self.get_cell_data_by_map(map_name=map_name, cell=cell)
        #col_names = self.get_column_to_export(alias=self.get_feature_type(), with_type=False)
        cols_number = len(export_column_names)
        data_dict = {}
        if col_data and len(col_data) > cols_number and is_demand_site == True:
            ##mandar mensaje de error a QGIS 
            pass
        
        values_to_save = min(cols_number, len(col_data)) if col_data else 0

        for i in range(cols_number):
            col_names = export_column_names[i]

            if i < values_to_save:
            # Asignamos el nombre de la geometría ganadora
                data_dict[col_names] = col_data[i]['name']
            else:
                # Rellenamos los "huecos" con cadenas vacías para mantener la integridad de la BD
                data_dict[col_names] = ''
        return data_dict


    ##filtra los datos de la celda que vienen del mapa 'map_name' 
    def get_cell_data_by_map(self, map_name: str, cell):
        ret = []
        if cell in self.cell_ids:
            ret = [d for d in self.cell_ids[cell]['data'] if d['map_name'] == map_name]
        return ret





