import time
import os
from collections import namedtuple
from qgis.core import QgsField, QgsVectorFileWriter
from qgis.PyQt.QtCore import QVariant

from .postprocessors.GeoChecker import GeoChecker
from .processors.CatchmentProcessor import CatchmentProcess
from .processors.DemandSiteProcessor import DemandSiteProcess
from .processors.GroundwaterProcessor import GroundwaterProcess
from .postprocessors.SuperpositionCheck import SuperpositionCheck
from .processors.RiverProcessor import RiverProcess
from  .utils.Visualizer import *
from .utils.UtilMisc import *
from .settings import *
from .settings import COLUMNS_FOR_SHP_EXPORT
from .utils.UtilMisc import UtilMisc

class AppKernel():
    """
    Initializes groundwater, catchment, rivers and demand sites processors. In addition, it initializes the kernel
    that processes the geometry, which will be used to validate the information from the geometry processor.

    It receives the inputs from UI interfaces.

    * Config file: ./config/config.json


    Attributes:
    ----------
    geo_processor : GeoKernel
        Used to read the surface scheme geometry (node and arc files).

    catchment_processor : CatchmentProcess
        Used to process catchment map.

    groundwater_processor : GroundwaterProcess
        Used to process groundwater map.

    demand_site_processor : DemandSiteProcess
        Used to process demand sites main map. That map is obtained from the surface scheme.
        Additionally it also processes additional maps with demand site areas.

    river_processor : RiverProcess
        Used to process the segments map obtained from rivers in surface scheme.

    consolidate_cells : Dict[namedtuple<Cell>, Dict[str, Any]]
        Used to consolidate groundwater, catchment, river and demand site cells in order to check them only once.

    config : ConfigApp
        Used to access to configuration parameters (constants, texts, input columns, ...).

    summary : SummaryInfo
        Used to access the results generated by AppKernel (errors, warnings, input parameters, statistics) and
        deliver them in a standard way.

    stats : Dict[str, str]
        Used to store the general process basic statistics.

    _err : ErrorManager
        Used to store errors and warnings found while running.

    __debug : bool
        Not used.

    _feature_type : str
        Text used to identify the main process (value: self.config.type_names[self.__class__.__name__]).


    Methods:
    -------
    get_feature_type(self)
        Get a name to identify processors or main program.

    set_config_field(self, catchment_field, modflow_field, groundwater_field, demand_site_field)
        Sets  geometry name columns in input maps to processors.

    export_to_shapefile(self, map_name, output_path)
        Export the 'map_name' map in ESRI Shapefile format (.shp) to the 'output_path' path.

    get_consolidate_cells(self)
        Unify all intersecting cells in processors in order to check them only once.

    init_linkage_file(self, linkage_name, linkage_new_name)
        Initialize the final grid map with the necessary and informative columns. The 'linkage_name' parameter
        is the input groundwater grid map and 'linkage_new_name' parameter is the final map name.

    mark_linkage_active(self, linkage_name, save_changes)
        Saves the cells information in the final map metadata ('linkage_name') to export.
        The 'save_changes' parameter sets the number of cells to review before committing the transaction.

    set_map_names(self)
        In case there is no error in the input files, register these files in the different processors to relate them
        to the vector maps to be imported.

    set_origin_in_node_arc_maps(self, map_names: list)
        Set lower left edge in vector map list 'map_names'.

    run(self)
        Runs the correct order of methods to perform the processing of the implemented processors.

    """

    def __init__(self, debug: bool = False):
        self.debug = debug

        self.catchment_processor = CatchmentProcess(debug=self.debug)
        self.groundwater_processor = GroundwaterProcess(debug=self.debug)
        self.river_processor = RiverProcess(debug=self.debug)
        self.demand_site_processor = DemandSiteProcess(debug=self.debug)
        self.stats = {}
        self.visualizer = Visualizer()

        
    def run_geo_checker(self, output_path: str, layers_dict: dict):
        geochecker_out = os.path.join(output_path, "geochecker_results")
        os.makedirs(geochecker_out, exist_ok=True)
        linkage_path = os.path.join(output_path, "linkage_final.shp")
        
        # .source() devuelve la ruta del archivo .shp en el disco
        arc_path = layers_dict['river']['river_layer'].source()
        node_path = layers_dict['river']['node_layer'].source()

        cells, arcs, nodes = UtilMisc.structure_creation(
            linkage_map=linkage_path,
            arc_map=arc_path,
            node_map=node_path,
            catch_name='CATCH',
            gw_name='GW',
            ds_prefix='DS'
        )

        geo_checker = GeoChecker(checks=[
            SuperpositionCheck(base_feature='groundwater', secondary_feature='catchment'),
            SuperpositionCheck(base_feature='groundwater', secondary_feature='demand_site')
        ], folder_path=geochecker_out)

        geo_checker.setup(cells, arcs, nodes)
        geo_checker.run()

    def consolidate_grid_attributes(self, grid_layer, layers_dict):
        """
        Toma los datos procesados de todas las entidades y los escribe 
        en la tabla de atributos de la capa de la malla.
        """
        # Extraccion de nombres (con validación defensiva)
        gw_layer_obj = layers_dict.get('gw', {}).get('gw_layer')
        nombre_mapa_gw = gw_layer_obj.name() if gw_layer_obj else None

        cat_layer_obj = layers_dict.get('catchment', {}).get('catchment_layer')
        nombre_mapa_catchment = cat_layer_obj.name() if cat_layer_obj else None

        river_layer_obj = layers_dict.get('river', {}).get('river_layer')
        nombre_mapa_river = river_layer_obj.name() if river_layer_obj else None

        # Para Sitios de Demanda: recolectamos los nombres reales de las capas que se procesaron
        # El map_name almacenado en las celdas proviene de well_layer.name() y area_layer.name()
        nombres_mapas_ds = []
        if 'ds' in layers_dict:
            # Los pozos usan la capa de nodos del río
            node_layer = layers_dict.get('river', {}).get('node_layer')
            if node_layer:
                nombres_mapas_ds.append(node_layer.name())
            # Las áreas de demanda usan sus propias capas
            for area_layer in layers_dict.get('ds', {}).get('demand_site_layers', []):
                nombres_mapas_ds.append(area_layer.name())


        # 1. Definir la estructura de columnas exacta que exige WEAP/MODFLOW
        # Ajusta los nombres de las llaves ('CATCH', 'DS1', etc.) según tus settings.py
        columnas_exportacion = COLUMNS_FOR_SHP_EXPORT

        # 2. Asegurarnos de que las columnas existan en la capa de la malla
        provider = grid_layer.dataProvider()
        campos_actuales = [field.name() for field in grid_layer.fields()]
        campos_nuevos = []

        for grupo_columnas in columnas_exportacion.values():
            for nombre_columna in grupo_columnas:
                if nombre_columna not in campos_actuales:
                    campos_nuevos.append(QgsField(nombre_columna, QVariant.String, len=50))
        
        if campos_nuevos:
            # Agregamos las columnas faltantes físicamente al Shapefile/Memoria
            provider.addAttributes(campos_nuevos)
            grid_layer.updateFields()

        # 3. Preparar el lote de actualizaciones
        # PyQGIS usa un diccionario { ID_Entidad: { Indice_Columna: Nuevo_Valor } }
        lote_actualizacion = {}
        
        # Necesitamos saber el índice (0, 1, 2...) de cada columna para el lote
        indices_columnas = {field.name(): grid_layer.fields().indexOf(field.name()) for field in grid_layer.fields()}

        # Nombres de columnas de la malla proporcionados por la interfaz
        col_row = layers_dict['grid']['col_row']
        col_col = layers_dict['grid']['col_col']

        # Definimos Cell una sola vez fuera del loop
        Cell = namedtuple('Cell', ['row', 'col'])

        # 4. Iterar sobre la malla y recolectar los datos ganadores
        for feature in grid_layer.getFeatures():
            fid = feature.id()
            
            celda_actual = Cell(feature[col_row], feature[col_col])

            atributos_celda = {}

            # -------------------------------------------------------------------------
            # EXTRACCIÓN DIRECTA Y A PRUEBA DE FALLOS
            # -------------------------------------------------------------------------
            
            # 1. Groundwater
            if self.groundwater_processor:
                gw_celda = self.groundwater_processor.cell_ids.get(celda_actual)
                if gw_celda and gw_celda.get('data'):
                    atributos_celda[columnas_exportacion['gw'][0]] = str(gw_celda['data'][0].get('name', ''))

            # 2. Catchment
            if self.catchment_processor:
                cat_celda = self.catchment_processor.cell_ids.get(celda_actual)
                if cat_celda and cat_celda.get('data'):
                    atributos_celda[columnas_exportacion['catchment'][0]] = str(cat_celda['data'][0].get('name', ''))

            # 3. Rivers
            if self.river_processor:
                riv_celda = self.river_processor.cell_ids.get(celda_actual)
                if riv_celda and riv_celda.get('data'):
                    atributos_celda[columnas_exportacion['river'][0]] = str(riv_celda['data'][0].get('name', ''))

            # 4. Demand Sites (Soporta múltiples pozos por celda)
            if self.demand_site_processor:
                ds_celda = self.demand_site_processor.cell_ids.get(celda_actual)
                if ds_celda and ds_celda.get('data'):
                    for i, registro in enumerate(ds_celda['data']):
                        if i < len(columnas_exportacion['ds']):
                            col_destino = columnas_exportacion['ds'][i]
                            atributos_celda[col_destino] = str(registro.get('name', ''))

            # 5. Mapear los nombres de columnas a sus índices numéricos para PyQGIS
            cambios_para_esta_celda = {}
            for nombre_col, valor in atributos_celda.items():
                if nombre_col in indices_columnas:
                    idx = indices_columnas[nombre_col]
                    cambios_para_esta_celda[idx] = valor
            
            # Guardamos los cambios de esta celda en el gran lote maestro
            if cambios_para_esta_celda:
                lote_actualizacion[fid] = cambios_para_esta_celda

        # 6. Ejecutar la escritura en bloque (¡El momento de la verdad!)
        # startEditing() y commitChanges() manejan las transacciones seguras en QGIS
        grid_layer.startEditing()
        provider.changeAttributeValues(lote_actualizacion)
        grid_layer.commitChanges()        



    def run(self, grid_layer, layers_dict, output_path, run_geochecker: bool = False):
        ts = time.time()

        # -------------------------------------------------------------------------------
        # Catchments Logic
        # -------------------------------------------------------------------------------
        if 'catchment' in layers_dict:
            self.catchment_processor.run(grid_layer, **layers_dict['catchment'], **layers_dict['grid'])

        # -------------------------------------------------------------------------------
        # GWS Logic
        # -------------------------------------------------------------------------------
        if 'gw' in layers_dict:
            self.groundwater_processor.run(grid_layer, **layers_dict['gw'], **layers_dict['grid'])

        # -------------------------------------------------------------------------------
        # Demand Sites Logic
        # -------------------------------------------------------------------------------
        if 'ds' in layers_dict:
            capa_nodos = layers_dict.get('river', {}).get('node_layer')
            col_nodos_nombre = layers_dict.get('river', {}).get('col_node_name')

            self.demand_site_processor.run(
                grid_layer=grid_layer,
                well_layer=capa_nodos,
                area_layers_list=layers_dict['ds']['demand_site_layers'],
                wells_txt_path=layers_dict['ds']['wells_file_path'],
                col_name=layers_dict['ds']['col_name'],
                col_well_name=col_nodos_nombre, 
                **layers_dict['grid']
            )

        # -------------------------------------------------------------------------------
        # Rivers Logic
        # -------------------------------------------------------------------------------
        if 'river' in layers_dict:
            self.river_processor.run(grid_layer, **layers_dict['river'], **layers_dict['grid'])

        # -------------------------------------------------------------------------------
        # General and Results Logic
        # -------------------------------------------------------------------------------
        # make a linkage map copy and format with the base linkage cols

        self.consolidate_grid_attributes(grid_layer, layers_dict)

        # EXPORTACION AL DISCO 
        
        # Construir la ruta final del archivo
        # Reemplazamos los slashes para evitar errores de parseo en OGR
        archivo_salida = os.path.join(output_path, "linkage_final.shp").replace("\\", "/")
        
        # Configurar motor de escritura vectorial de QGIS 3
        opciones = QgsVectorFileWriter.SaveVectorOptions()
        opciones.driverName = "ESRI Shapefile"
        opciones.fileEncoding = "UTF-8"
        opciones.actionOnExistingFile = QgsVectorFileWriter.CreateOrOverwriteFile
        
        # Ejecutar la clonación al disco (Captura segura de la tupla)
        resultado_escritura = QgsVectorFileWriter.writeAsVectorFormatV3(
            layer=grid_layer,
            fileName=archivo_salida,
            transformContext=grid_layer.transformContext(),
            options=opciones
        )
        
        # Extraer estrictamente los dos primeros valores ignorando el resto
        codigo_error = resultado_escritura[0]
        mensaje = resultado_escritura[1]
        
        if codigo_error != QgsVectorFileWriter.NoError:
            raise IOError(f"Critical I/O error. Could not save the final file to the output path: {mensaje}")
        # =================================================

        ## no implementado aun
        if run_geochecker:
            self.output_path = output_path
            self.run_geo_checker(output_path, layers_dict)
            

        te = time.time()
        self.stats['TOTAL_TIME'] = f"{te - ts:.2f} seg"

        self.visualizer.set_result_path(output_path)
        

